spring:
  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-i6kte-kr.vpc-pub-cdb.ntruss.com:3306/ga
    username: ${GA_MYSQL_ID}
    password: ${GA_MYSQL_PW}
  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

mail:
  address:
    admin: utest3912@gmail.com # admin mail address

jwt:
  key: ${JWT_SECRET_KEY}                # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30   # access-token 유효시간 : 30분
  refresh-token-expiration-minutes: 420 # sercret-token 유효시간 : 420분(7시간)
