server:
  port: 8080
  error:
    include-exception: true     # 응답에 exception의 내용을 포함할지 여부
    path: '/error'               # 응답을 처리할 Handler의 경로
    whitelabel:
      enabled: true             # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부

# logging setting
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DX_DB_URL}
    username: ${DX_DB_NM}
    password: ${DX_DB_PW}

  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail: # 메일 전송 설정
    host: smtp.gmail.com
    port: 587 # 465 또는 587 포트 사용 가능(SMTP)
    username: ${DX_MAIL_NAME} # 전송할 이메일
    password: ${DX_MAIL_PW} # 생성된 비밀번호 (참고 사이트 : https://hyunmin1906.tistory.com/276)
    properties.mail.smtp:
      auth: true
      timeout: 25000
      starttls.enable: true
    protocol: smtp
  output: # log color
    ansi:
      enabled: always

mail:
  address:
    admin: ${DX_MAIL_ADMIN} # admin mail address

jwt:
  key: ${DX_JWT_KEY}              # 민감한 정보는 시스템 환경 변수에서 로드한다.
  #  access-token-expiration-minutes: 30   # access-token 유효시간 : 30분
  access-token-expiration-minutes: 10000   # access-token 유효시간 : 10000분 -> 테스로 변경
  refresh-token-expiration-minutes: 420 # sercret-token 유효시간 : 420분(7시간)


cloud:
  aws:
    s3:
      bucket: insureprobucket
    credentials:
      access-key: ${DX_S3_AK}
      secret-key: ${DX_S3_SK}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

kakao:
  key: ${DX_KAKAO_KEY}

# micrometer
management:
  server:
    port: 9292
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: "*"